### ISSUE TITLE
What constitutes as a value in the context of a form? 

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui-forms#151]
### Some background info:
The React Final Form docs [state the following](https://final-form.org/docs/react-final-form/types/FieldProps#allownull):
> By default, if your value is null, <Field/> will convert it to '', to ensure controlled inputs.

We currently also have a `required` helper looks like this:
```javascript
export const requiredMessage = i18n.t('Required')
export const required = value => (value ? undefined : requiredMessage)
```
Since `required` should return an error if the field "does not have a value", it is important we define a non-value correctly in the context of a form.

#### Empty field
- `null`
- `undefined`
- `''` (empty string) (see reference to the RFF docs above)

#### Valid values
- `0` (number zero) (imagine a custom input that deals with numeric data: `0` would be a valid value)
- `false` (imagine a switch that toggles a value from true to false, false is still a valid value)
- All other truthy values

#### Code
Based on the reasoning above, we could rewrite this function as follows:
```javascript
export const requiredMessage = i18n.t('Required')
export const required = value =>
    typeof value === 'undefined' || value === null || value === ''
        ? requiredMessage
        : undefined

```

**Comment by ghost** [comment]
Hendrik and I talked a bit about this on slack. I think I'd prefer having separate, more specific validators, to address this issue. So for example:

- `requiredNumber`: checks if it's a number, accepts 0 as well
- `requiredNonEmptyString`: checks if it's a non-empty string
- add more as needed, say you need `requiredPositiveNumber` for example, etc.

That'd allow for very simple, easily unit-testable validators, that (should) clearly specify what they do by their name. So that when you're reading through a form you don't have to look up what a validator does exactly. I think that'll lead to less dev errors.

**Comment by HendrikThePendric** [comment]
A thought that came up after that Slack conversation:
What I quite like about the current one-size-fits-all implementation is that it would lead to a very composable mechanism. See the example below for illustration, which assumes we have a `required`, `string` and `number` validator:
- Want a required string `composeValidators(required, string)` 
- A required number `composeValidators(required, number)`

My preference would be to at least try this as our first (perhaps overly naive) approach. If it turns out that it is actually impossible to define a general rule for an "empty field" we move to the type-specific approach.

**Comment by Mohammer5** [comment]
@ismay Can you explain why you think having these validators is beneficial? One benefit I could extract from your comment is: fewer bugs (is there a difference between bug and dev error?)

What would be a bit confusing to me is that if we need to compose several validators, which one should be the "required" one? Or should they all be "required"? Let's say a value should match a pattern `createEqualTo(/^[ahcdefg]+$/)`, should only have a certain length `createLengthRange(1, 5)`, it's look more natural to me to do:

```js
composeValidators(
  required,
  createEqualTo(/^[ahcdefg]+$/)
  createLengthRange(1, 5),
)
```

Than this:

```js
composeValidators(
  createRequiredEqualTo(/^[ahcdefg]+$/)
  createRequiredLengthRange(1, 5),
)

// or
composeValidators(
  createRequiredEqualTo(/^[ahcdefg]+$/)
  createLengthRange(1, 5),
)

// or
composeValidators(
  createEqualTo(/^[ahcdefg]+$/)
  createRequiredLengthRange(1, 5),
)
```

**Comment by ghost** [comment]
We talked a bit about this on Slack. I left a comment in the PR here: https://github.com/dhis2/ui-forms/pull/164#issuecomment-567394443. So since composition is necessary because of the large amount of unique checks we expect to do, we could go with naming required more specifically. That'd communicate its function clearly and at the same time scope what it does for us more precisely.

**Comment by HendrikThePendric** [comment]
- We are building on top of react-final-form so we should try to use patterns recommended by that ecosystem
- If you look at the react-final-form docs and look at the "Field-Level-Validation" section examples of the examples you see the exact same approach as we have implemented https://final-form.org/docs/react-final-form/examples/field-level-validation

Now, I happen to really like this approach, because:
- every validator does only one thing
- because of this you can combine these very well to suit a specific use-case

And I don't like the approach you are suggestion because it means that validators start doing more than one thing.

But regardless of our difference in opinion, I think we should try to adapt to what seems to be a common pattern in the technology/ecosystem we are adopting.
